#!/usr/bin/env bash
# Requires you to have exported 2 environment variables:
# export BITBUCKET_USER=my_bitbucket_username
# export BITBUCKET_TOKEN=my_bitbucket_app_password
#
# c.f. https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/
# Requires:
# - jq   : https://github.com/jqlang/jq
# - jf   : https://github.com/sayanarijit/jf (to json encode multiline comments)
# - curl : why of course it does!, why haven't you got it?

set -eo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
#shellcheck disable=SC1090
source "$SCRIPT_DIR/includes/common"

PREFERRED_ACTIONS_LIST="co|completion|whoami|list|prx|"

build_actions() {
  for f in "$SCRIPT_DIR"/includes/bb_*; do
    #shellcheck disable=SC1090
    source "$f"
    name=$(basename "$f")
    PREFERRED_ACTIONS_LIST+="${name#bb_}|"
  done
  PREFERRED_ACTIONS_LIST=${PREFERRED_ACTIONS_LIST%?}
}

action_squash-msg() {
  echo -e "\n>>> use of deprecated 'squash-msg', try 'message' instead"
  action_message "$@"
}

action_co() {
  action_checkout "$@"
}

action_completion() {
  cat "${SCRIPT_DIR}/completion.sh"
}

action_whoami() {
  curl $CURL_FLAGS --user "$CURL_AUTH" -H "$CURL_HEADER_ACCEPT" "$BITBUCKET_API_BASE/user" | jq 'del (.links)'
}

action_list() {
  __emit_pr_list "$@" | sort | column -s "|" -t -N "ID,TITLE,URL"
}

build_actions
ACTION_LIST="$PREFERRED_ACTIONS_LIST|squash-msg"
ACTION=${1:-help}
if [[ -z "$GIT_REMOTE" && "$ACTION" != "completion" ]]; then
  ACTION="help"
fi

if [[ "$#" -ne "0" ]]; then shift; fi
if [[ ! "${ACTION}" =~ ^$ACTION_LIST$ ]]; then
  echo "Invalid action [$ACTION]"
  action_help
fi
action_"$ACTION" "$@"
cleanup
