#!/usr/bin/env bash

action_checkout() {
  local pr_number=${1:-}
  if [[ -z "$pr_number" ]]; then
    pr_list=$(__emit_pr_list -q)
    if [[ -z "$pr_list" ]]; then
        >&2 echo "bb-pr checkout: no PRS found, nothing to do."
        exit 1
    fi
    if type -p fzf > /dev/null; then
        selected_pr=$(fzf --height ~100% --prompt="Select PR > " <<< "${pr_list}")
    else
        >&2 echo "bb-pr checkout: need 'fzf' for fuzzy search if no pr_number"
        exit 1
    fi
    pr_number=$(cut -d'|' -f1 <<< "${selected_pr}")
  fi

  if [[ -z "$pr_number" ]]; then
    echo ">>> No PR"
    exit 1
  fi

  local pull_request_url="$BITBUCKET_REPO_API_URL/$BITBUCKET_SLUG/pullrequests/$pr_number"
  body=$(curl "${CURL_FLAGS[@]}" --user "$CURL_AUTH" -H "$CURL_HEADER_ACCEPT" "$pull_request_url")

  branch=$(echo "$body" | jq --raw-output ".source.branch.name")

  git fetch --all
  git switch "$branch"
}
