#!/usr/bin/env bash

# Make a PR draft.
#shellcheck disable=SC2002
action_draft() {
  local pr_number=$1
  pr_number=$(get_pr_number "$pr_number")
  if [[ -z "$pr_number" ]]; then
    echo ">>> No PR"
    exit 1
  fi
  local pull_request_url="$BITBUCKET_REPO_API_URL/$BITBUCKET_SLUG/pullrequests/$pr_number"
  local pr_body='
{
  "draft": true,
  "reviewers": []
}'
  __bb_rest_with_callback \
    "__draft_success_output" \
    "__draft_failure_output" \
    "" \
    -X PUT -H "$CURL_HEADER_CTYPE" "$pull_request_url" "--data" "$pr_body"
}

__draft_success_output() {
  jq --raw-output '"Draft Mode: \(.draft)"'
}

__draft_failure_output() {
  jq --raw-output '.error.message'
}
