#!/usr/bin/env bash

action_help() {
  cat <<EOF

Tool that helps management of bitbucket pull requests from the commandline

Usage: $(basename "$0") [$PREFERRED_ACTIONS_LIST] [options]
  help         : show this help
  list         : list (open) PRs in this repo
  checkout     : check out a pull request in git
  co           : alias for checkout
  message      : copy a reasonable message to the clipboard for merging a PR
                 (squash-msg still exists for backwards compatibility but
                 will be removed real soon now to avoid conflicts with completion
                 convenience)
  squash-merge : merge the PR using the message from 'squash-msg'
  approve      : approve a PR (though should you from the CLI?)
  unapprove    : remove your approval
  decline      : decline a PR
  close-branch : change the 'close_source_branch' field
  completion   : returns command bash completion
  status       : shows the overall status of the requested PR
  whoami       : shows some information about your current user
                 - requires 'account read' scope
  ready        : mark a PR as ready for review, which means that
                 .bitbucket/bitbucket-pr.yml is parsed and the
                 uuids are added as reviewers.
                 - The PR author will be removed from the potential
                   list of reviewers.
                 - This will change the PR from draft to ready
  draft        : Remove all the reviewers and mark as draft

'message' | 'squash-merge' | 'approve' | 'unapprove' | 'decline'
'close-branch' | 'status' | 'ready' | 'draft'

Without an argument, the pull request that belongs to the current branch is used.

Arguments
  <PR> The PR number to operate on.

'close-branch' can toggle true or false (default true)
  -c : true|false (e.g. -c false) to toggle the state

'squash-merge' can do dangerous things
  -D : force close the branch regardless of the PR setting. If not
       specified then the PR will be merged according to the PR
       settings.

'list' can additionally filter by state
  -s : the state (e.g. -s OPEN) OPEN|MERGED|DECLINED|SUPERSEDED
       If you get it wrong, you'll get all the PRs which may take
       longer than you want. Defaults to 'OPEN'

Examples
If we are on the branch 'fix/owasp'

# Squash Merge the PR associated with 'fix/owasp' and close (delete) the source branch
# The local branch 'fix/owasp' is deleted and you will end up on the 'main' branch
bsh ❯ bb-pr squash-merge -D

# Squash Merge the PR associated with 'feat/owasp' according its PR settings
# The local branch 'fix/owasp' is deleted and you will end up on the 'main' branch
bsh ❯ bb-pr squash-merge

# Squash Merge the PR#5 leaving you on the 'feat/owasp'
bsh ❯ bb-pr squash-merge 5

# Squash Merge the PR#5 deleting the source branch leaving you on the 'feat/owasp'
bsh ❯ bb-pr squash-merge -D 5

EOF
  exit 2
}
