#!/usr/bin/env bash


action_message() {
  local pr_number=$1
  local squash_merge_msg

  pr_number=$(get_pr_number "$pr_number")
  if [[ -z "$pr_number" ]]; then
    echo ">>> No PR"
    exit 1
  fi
  squash_merge_msg=$(__emit_squash_merge_msg "$pr_number")
  echo "---"
  echo "$squash_merge_msg"
  echo "---"
  echo "is now in your clipboard"
  # shellcheck disable=SC2091
  echo "$squash_merge_msg" | eval "$(clipboard_exe)"

}

